# mlpeople/statistics/__init__.py
from .descriptive import (
    get_mean,
    get_median,
    get_variance,
    get_std,
    get_covariance,
    get_corrcoef,
)
from .distribution import (
    doane_bins,
    fit_distributions,
    plot_fitted_histogram,
    qqplot_sample_vs_sample,
    qqplot_from_dataframe,
    qq_plot_sm,
    qq_plot_st,
    qqplot_all_lines,
)
from .clt_simulation import (
    clt_sample_proportions,
    clt_sample_means,
    clt_from_normal_population,
    clt_from_categorical_population,
    clt_from_bernoulli_population,
)
from .hypothesis_tests import (
    z_test,
    z_test_summary,
    t_test,
    t_test_for_sample,
    t_test_summary,
    plot_z_vs_t,
    two_sample_z_test,
    two_sample_t_test,
)

from .pca import (
    pca_from_scratch,
    plot_explained_variance,
    plot_cumulative_variance,
    plot_variance_bars,
    plot_3d_original,
    plot_3d_pca,
    plot_pca_axes,
    reconstruction_error_curve,
    plot_reconstruction_error,
    plot_pca_loadings,
    plot_sorted_loadings,
)

__all__ = [
    "get_mean",
    "get_median",
    "get_variance",
    "get_std",
    "get_covariance",
    "get_corrcoef",
    "doane_bins",
    "fit_distributions",
    "plot_fitted_histogram",
    "qqplot_sample_vs_sample",
    "qqplot_from_dataframe",
    "qq_plot_sm",
    "qq_plot_st",
    "qqplot_all_lines",
    "clt_sample_proportions",
    "clt_sample_means",
    "clt_from_normal_population",
    "clt_from_categorical_population",
    "clt_from_bernoulli_population",
    "z_test",
    "z_test_summary",
    "t_test",
    "t_test_for_sample",
    "t_test_summary",
    "plot_z_vs_t",
    "two_sample_z_test",
    "two_sample_t_test",
    "pca_from_scratch",
    "plot_explained_variance",
    "plot_cumulative_variance",
    "plot_variance_bars",
    "plot_3d_original",
    "plot_3d_pca",
    "plot_pca_axes",
    "reconstruction_error_curve",
    "plot_reconstruction_error",
    "plot_pca_loadings",
    "plot_sorted_loadings",
]
